---
# Project information
site_name: Hackspace Wiki
site_author: Leigh Hackspace
site_url: https://leigh-hackspace.github.io/HackspaceWiki/

# Repository
repo_name: leigh-hackspace/HackspaceWiki
repo_url: https://github.com/leigh-hackspace/HackspaceWiki
edit_uri: "edit/main/docs/"

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/tablesort.js

extra_css:
  - assets/extra.css

theme:
  name: material
  logo: assets/logo.svg
  palette:
    scheme: default
    primary: black
    accent: red
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top

docs_dir: ./docs

copyright: Copyright &copy; 2023 Leigh Hackspace CIC - <a href="#__consent">Change cookie settings</a>
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/leighhack/shared_invite/enQtNDYzMjEyMDMxNDExLTE1MWY5N2IwMzdhMzQ0ZWFiNDkyNzJmMGM1ZmFkODcwMGM5ODFmYmI4MjhmM2JiMWEyY2E3NTRjMTQzMzljZWU
    - icon: fontawesome/brands/github
      link: https://github.com/leigh-hackspace
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@leigh_hackspace
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - search
  - table-reader
  - git-revision-date-localized:
      enable_creation_date: true

# Extensions
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Welcome:
      - index.md
      - Location: welcome/location.md
      - Nearby Services: welcome/nearby_services.md
  - Membership:
      - Joining The Hackspace: membership/joining.md
      - Membership Types: membership/membership_types.md
      - Access: membership/access.md
      - Rules: membership/rules.md
      - Disputes: membership/disputes.md
      - Useful Contacts: membership/useful_contacts.md
  - Facilities:
      - facilities/index.md
      - Main Space: facilities/main_space.md
      - Pi Room: facilities/pi_room.md
      - Classroom: facilities/classroom.md
      - Workshop:
        - facilities/workshop/index.md
        - Tools List: facilities/workshop/tool_list.md
        - Guides:
          - Bandsaw: facilities/workshop/bandsaw.md
          - Table Saw: facilities/workshop/table_saw.md
          - Woodturning Lathe: facilities/workshop/woodturning_lathe.md
      - Fabrication: facilities/fabrication.md
      - Electronics: facilities/electronics.md
      - Dark Room: facilities/dark_room.md
      - Crafts Space: facilities/crafts_space.md
      - Social Space: facilities/social_space.md
      - Artist Pods: facilities/artist_pods.md
  - Infrastructure:
      - Internal Services: infrastructure/internal_services.md
      - Network Layout: infrastructure/network_layout.md
      - VPN: infrastructure/vpn.md
